name: Excavator

on:
    schedule:
        - cron: '0 */6 * * *'
    workflow_dispatch:

jobs:
    excavate:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Excavator
              uses: ScoopInstaller/GithubActions@main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
